apiVersion: v1
kind: Pod
metadata:
  labels:
    run: slave
  name: slave
spec:
  containers:
  - name: node 
    image: node:lts-alpine
    command:
    - cat
    tty: true
  - name: kubectl
    image: alpine 
    command:
    - cat 
    tty: true
    volumeMounts:
    - name: kube
      mountPath: "/home/.kube"
      readOnly: true
  - name: kaniko 
    image: gcr.io/kaniko-project/executor:debug
    command:
    - cat 
    tty: true
    volumeMounts:
      - name: kaniko-secret 
        mountPath: /kaniko/.docker 
  serviceAccountName: jenkins-pipeline
  volumes:
  - name: kaniko-secret 
    secret: 
      secretName: "docker-cred-gm5hkcc2mt"
      items:
      - key: .dockerconfigjson 
        path: config.json
  - name: kube
    secret:
      secretName: "kube-config-bhg52khm6t"
  